# Generated by Django 3.1.5 on 2021-12-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_type', to='package.packagetype'),
            preserve_default=False,
        ),
    ]
