# Generated by Django 3.1.5 on 2021-12-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
