# Generated by Django 3.1.5 on 2021-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'member'), (2, 'coach'), (3, 'admin')], null=True),
        ),
    ]
