# Generated by Django 3.1.5 on 2021-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211215_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
