# Generated by Django 3.1.5 on 2021-12-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211215_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'female'), (1, 'male')], default=0),
            preserve_default=False,
        ),
    ]
