# Generated by Django 3.1.5 on 2021-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='education_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'High'), (3, 'College'), (4, 'Sport Academy'), (5, 'Bachelor'), (6, 'Master'), (7, 'Doctorate')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'coach'), (3, 'admin')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
