# Generated by Django 3.1.5 on 2022-01-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211224_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'coach'), (3, 'admin')], default=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'female'), (1, 'male')], null=True),
        ),
    ]
