# Generated by Django 3.1.5 on 2021-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='account.Member'),
        ),
    ]
