# Generated by Django 3.1.5 on 2022-03-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted_time',
            new_name='update_time',
        ),
    ]
