# Generated by Django 3.1.5 on 2021-11-23 13:25

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branchs'},
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
